[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "c90651be5cdaf32dfe0edbdc05dfe3c678e9c926"
libgfortran_version = "5.0.0"
os = "macos"

    [[SIFDecode.download]]
    sha256 = "88d4f7656848b3e0f22714968ea270e78f8e2b8d704a75e6fadbe1a132c9f590"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "f30673b2bbf73ebc180740d97ddf8cd464273f36"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "d2dcc5aefd62ba45ec5dd3f7d0e3d14d5069f046f0c7b63d6e9cfbd859112155"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "5952d29dce567e2741330d22cb7f54ee08fcda94"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "108d5fdd9c85a942aefb91c34ffcb9c0d52e58f2335a3ae13ae81f51c2cc3549"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "f60d12ef4c1b47e5bdf9d034b82dcc4e865c676b"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SIFDecode.download]]
    sha256 = "09a884038ef2605f1f0102e3759fc60bf550bead48a844300755aa4055cf02bd"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e8e389c4c46291198132158bea70bfd7756b8f39"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "6f2d59bbc8cb2dbc707ea6374320799a7608b00a35e626ad11f01844dcd75101"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c4645e66f1fc77aaed626cfbfd384322de8d8bf0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "b817978bd086628076cb5b79615286e29d8172fa228f95271eb84ab564cd8f0e"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "274d2a14897391e0ae86e11f562552b4a75aa921"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "c246fd60084830c1ab2a50d0591b0eca5e5e6599b9e14d41ea1f079561f2f3ed"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b7d72f474ef0f073b60764f7dda4faa039f0f73a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "e5e107da15a6362658d7508ba9e2059969829cbd06a02dba8f2cd9ae84fa86b5"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "ec78e5d449f8277443a0ef9110f1993d9d162cff"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "c64ae77e5aa804a5eb4bc67e494413dea02d58f6a981d69336762a33d3ba85a7"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "bf59f34282a735b0cd1d03572e681f19d07cc0c1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "d65bfe5dff8ce7e580d9cac1dc9d43e7a01542c7bce0bf2f15862b9889a70cb5"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.i686-linux-musl-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "b9150a78640115243aefb16c2b327d960eefbce0"
libgfortran_version = "5.0.0"
os = "windows"

    [[SIFDecode.download]]
    sha256 = "3831613c68f98db1fa65a7ef9928f6d7c82b7febb4a4e65c9cf2db1b9a7552ff"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "powerpc64le"
git-tree-sha1 = "32929ebcfd2ac14b4cd18c73ad1999ce01bc8c6b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "c8b41a6c4f72eea3f72a59fbe78aa4b3c7d9dbda33e11a7f9b3dda035728e5c2"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "riscv64"
git-tree-sha1 = "44ea31b4f766aa87aa3341b6cc7cc1c304893f20"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "c68422f5ee91f262d5035a3b2a273ba5fbb0c0a735bc632e3cf76cb3febd64fa"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.riscv64-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "b216a191ce0f9de178ad68a8f725316991b8c15f"
libgfortran_version = "5.0.0"
os = "macos"

    [[SIFDecode.download]]
    sha256 = "b5e4f2d33dc6c92661a8260f2a62cbd48db4997cebca0c8574029cf61c872db2"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "d6a32f5325024453d51a5c6335d5f9152a79089e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "899863dfd8c0f28080594e354bbb61415f5ccf1d251ce1eb96986b5be74cea16"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "e724e8c678679ce99004aacea719c5bda8345f1d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "b0428a0a2754a36bb0f9e5e07fc23c7170a457c2b580825d1e7f57b714869871"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "99416be1d1c74ff4c9fdec7e38b29a0cb829ec88"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SIFDecode.download]]
    sha256 = "2b7e9899f4dff254f09abe12c895c19bb2338baa143789cc639ccf831675201c"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "6d253df6198bbb556b510e2d68a7b086f31e64fb"
libgfortran_version = "5.0.0"
os = "windows"

    [[SIFDecode.download]]
    sha256 = "99bfe4786121aaaabd9f99b371909d59a322c8e11d3498706ea9f43bee0b5479"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.0+0/SIFDecode.v3.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
