[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "b3e7cd31af1efe5ed626a6ed44664a3f5bc0c478"
libgfortran_version = "5.0.0"
os = "macos"

    [[SIFDecode.download]]
    sha256 = "1fabda517297d41e4483f4533d9fbaadfe6e72bedd27197dd799e1100f796ef2"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "d17864111b8d43edd6c06e4c6cdf634430b78fdc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "2efd14f83afbf43290d331e9b8596fa815a3850aaa912fb53706c60d5890da3c"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "2a96d8cf3aa7c182f0fdf9d1190c978bce264526"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "744007009db0b6e10a8c993bb10c088d46ba0eb085ccc3faa66f4306edb3c308"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "12bcbfa2092179a4eb40e2723ad8d26044554703"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SIFDecode.download]]
    sha256 = "da520e45a85ba88926849e38e0cf29f873beab9b930d8c4e8a2020e292510639"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f05507006cbb62bc42b6ddf26c6e935d85765794"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "3cc56fda728c717de09df23e0046cc5bf3dd427f9b813459af60c58547f7b325"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2a499ac6827ecded01eda302cae718dcd6aaf2ea"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "119f40e9a19b43c111117887ef29d0adecc21c536e1916b9eb93319d684666aa"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0c31e80ebf948dbd05b418cd0a83bd9a82689b6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "e2f877d63b81201485aac2e4a32f9a6a43a908fd65a0c641ea86786ec0461b30"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "09a96b684ce20f31084868bd5aca7293fa08ab53"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "8642eb261203d00123a7e1191de22ca6a1970849b9a6a89aae6eab5cbaba8dd2"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "6d6b660d0e4429b38215c29e84f4f83839bcd7bc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "a295d872e45b0ceb5e64d1178ce7bbd0c6a32da220ab0fa5f1b3868b6b5f4070"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "d67d14285bdf773f52d7455bf22cc2247427b9a6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "2dc6d55c7964566c576a05d1763069fecc2430fd4881c4d78b5e7798b75b308a"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "1d1817bf13c42d1cb5c3f4b8d00f715de91f083c"
libgfortran_version = "5.0.0"
os = "windows"

    [[SIFDecode.download]]
    sha256 = "815e89a6d41a103ad3fcc516c7c955da70e139ef390af6828e2ab8e18bc862ae"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "powerpc64le"
git-tree-sha1 = "47e6c9ac1e5492f7e93f69ab34600fc427dbb383"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "ae0ae4796174145e136c58a97f962c52ed3364ca939e4f55ea9876c68c7a9ba1"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "riscv64"
git-tree-sha1 = "4d00b8dc704809ece2644b2a1854d5d68285fe94"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "4b9d4fe524c3bd0f55b1d1f445561d06d7edc070ce7ce7a2d5607df50e2d41ef"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.riscv64-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "a009d7dbc852a4e630fbccb018c2a07c50295f71"
libgfortran_version = "5.0.0"
os = "macos"

    [[SIFDecode.download]]
    sha256 = "35edefd2ee465c8fe8cc5f06bacbf83418afdb3102cdf762edf7b78ee3647d4b"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "1baf57b6c9116b4151a992139219040603f73128"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "17206ab0f19a662b4ded7da6b2137ebffa4ac5b29f60f3232f1da98393b5bc0e"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "2d060799f3e323c65d189b24f021d4636e5faa9c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "4141a8d137b4c4c2252ec891dbb73a35c449ed21c77bf6edd5f46e6f2379b426"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "e7bf2219ddd8414f1ad983e0c90b2404aa384fc5"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SIFDecode.download]]
    sha256 = "f9ad1ccdf63e965a277c16b27a317b56d7983dc6b9b5ba64d612289818ab6de7"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "67f8b16e6111216e6669df77b44bb054d3369efc"
libgfortran_version = "5.0.0"
os = "windows"

    [[SIFDecode.download]]
    sha256 = "153e8921e3145f75584d3a3abfb1a8c8d63edddf5b8e79bc8876a8521541ff1d"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.0.0+0/SIFDecode.v3.0.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
