[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "9e16b5eb7b59096b041366f4cbc2b9849cf437d0"
libgfortran_version = "5.0.0"
os = "macos"

    [[SIFDecode.download]]
    sha256 = "f8befd4f03ae19fe5877ebdacf28627592c5776fa65c20f5e7ffef22f78a0d45"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "3f6195e0baf98bbe94829155abebf789acce79e4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "d768a19a1bd3c2aa51f5e457402f9c3dffb69d052fb3a8998443adee0d8ab930"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "79b8632f22d386ec336e7d425c49060216dddbae"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "a9c522935e88de3a695e96128659e34a9c30412a99d0496b38c31615d885a246"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "d36d0f1fa743a827834968b9c394dfb971b69073"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "bee3892f8baa70fe0f41cfae2ec5711dfc6ab99e8fbf5a10134d75addbaec9cd"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "7def89aa684f9d27c37a8605777016a268538e08"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "2eb1057c3f9cb92f8734abfa545b26b1cca976cb43ccbe1f594ac1ecce61783f"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c77ab20368b3b1f8c4d8517865909895e12a9c74"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "74e5760ceebd7ab4c24178be2890cc91e2951a68f26db7e82207d84a9ef2d4ce"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5bb73bd46216db53becef02b5c3921fc929e8006"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "f4e38b79001a7695550f359bb0343b53f62b541f66874be4378716ac55133ff5"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f52f3e4a63f1aee9acc6ed84312f12d10ecad4ee"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "5790c79c8b6882488662f08233b7750faad1a903e9ec83d5b6f1e5e179fcdf7c"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "622ab7eeab70bc58e0beb06007045782a2fec661"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "0935e56cb3e9fa7ac28f930b326505d1f30a086c672ed8af0da640b1354b8c0e"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eec1759e51c090a0065b27d03a5f663a19e1ccfb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "56c635ac6f4c9c423e5b136025f5a342e00ecd0bc69c6c55e12a12255d9b30d2"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1d5e837417475aafe7d609b73d77f8cf91af9526"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "ac5612b3344253a43dd7589f7ac94217f4eeb480428c2edfbe0334edd23b94c8"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5d562a2c876d12c85604c01e47e6e03ffe8e0b69"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "8ca7dfb36b23eb0bfe0239f16ffdedb7a67ca9236d42c5254792b9863c11c069"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7051b47bd6f0bba1ef71a61fe1ccedafcf46c8ea"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "416cbc8b40e21efec5faa517b5d0cdb4e68f6d085e424ab7c55abffd9fb31975"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "8e7ca5a21003d213f99681a24cdd02de24782e4c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "a29e6dedc7f3bc9ad3758b7c63cb1885451fa74e1c6370fd6a3c17fb6ed093b2"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.i686-linux-gnu-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "02ae27dab92890c2dcf21416572900cab40308f8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "b452b3dcc82b0fe2105d9fbdce4240333b54c449d4b2cf89d7ff1996893843a8"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.i686-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "d6307a5be1d4b854108ea3c70d8a40c299b9bd17"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "627758b220477f41d5f9415f5decadb38a69a4aeb0018f3c7df9c5fcc50dc933"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.i686-linux-musl-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "5da59c8255ac030dc3bc25aa3188490b8df16077"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "facbad8dff3135d2c2db3a36e4b8b28d566caace97f98383e1fbb58ccc477752"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.i686-linux-musl-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "669471f22d262021d032d3d2360765b26df0f3ae"
libgfortran_version = "4.0.0"
os = "windows"

    [[SIFDecode.download]]
    sha256 = "6e234eeb0bd5905460a952b0ff879f49f4495c5cbb62232bdbb94abe3a0ad450"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "b059b1eb051f68c77dc2ed15d49a94ffe2d59959"
libgfortran_version = "5.0.0"
os = "windows"

    [[SIFDecode.download]]
    sha256 = "73f62c356413421ed5b3e0ccf10bba71239b4af7b1555e0065fcfcd3dbd49d98"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "powerpc64le"
git-tree-sha1 = "256d479aff9471a7d08605739a3ec1e93e8450eb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "d9ebb3e40ad9e3757ad4eee8daaca1f7f4d5c4b46c4aa72043fa975a4c76e709"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "powerpc64le"
git-tree-sha1 = "cc6e693ca1e9a5d0d3fd02005b80630d3fb3d783"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "2b0e3113f55a8a169e9e1872eb12ea869a7b5af2fbf5f3f64ba11521db931681"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "9a2933a517ff8ab9e0344bc3b8f9e5375aae6d51"
libgfortran_version = "4.0.0"
os = "macos"

    [[SIFDecode.download]]
    sha256 = "056cccfdb44df81225d477df408cc91b9df609cb56972238173421ca8e2a4dde"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "3cdc4671ae995992397cc5dc3ef11855a053f9e2"
libgfortran_version = "5.0.0"
os = "macos"

    [[SIFDecode.download]]
    sha256 = "127b91c999be4da8bc23ce92f1a44dd973fdb49bd82af72e7c6e4da02ff52980"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "aa284bca1ce256d8d5bc4da9b597df15f8c3fc50"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "d79368657804919935e6b2b3377922c28ef0cf76e172d0aaafaf9c80f7222575"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "eef0fb4be154c95aa8fac1301b3e6a0bdf45ba5d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "0eb627c8f235d0c304f6e9eb61cfaa008f8b9028f571d4bc3dac61df8b036103"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "16c794360347cd68f835fefb4ee3c111eb663891"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "7c62ec6adfe4418548d81d31dd50e7dd8b88b760f9133b616f1da60c808a59bc"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "89b01349942569b5255f10ec26615b3d17926835"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "9eeb443df8c02d432fee600671900b2020cda75f6853b11ca5567ba724575fe5"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "c68f8e2f44d8fdff090b3947e00a7b0f618f3da1"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SIFDecode.download]]
    sha256 = "e50c8e4e2953be8e57fa9e42d1d7bab11e519ed5b35b4edea11b93e7504805b1"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "570196b0c95e6ad1ae24cafd7f12cd35999dcf31"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SIFDecode.download]]
    sha256 = "aab5bdbcf727d80fadbd5948f0e400065f61696311a018a484a2b1bddb945d6d"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "fcef623e3ea5f26bba00695e3800b6abe5466818"
libgfortran_version = "4.0.0"
os = "windows"

    [[SIFDecode.download]]
    sha256 = "52505f3a65d34104f0726d40f59adad4b7c83a9d126b679bc00632e4024d33b5"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "79ef797cc695b8c88aa9ff34836f75128a07bb5f"
libgfortran_version = "5.0.0"
os = "windows"

    [[SIFDecode.download]]
    sha256 = "9a555f1a6b384d1d866fcff0dbc6e7542e03399cb71b042baa4feb53313992b6"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v2.5.1+0/SIFDecode.v2.5.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
