[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "e92a50b05e5b36d5480abae7879b7dd47735479c"
libgfortran_version = "5.0.0"
os = "macos"

    [[SIFDecode.download]]
    sha256 = "edbd4c575c9db0be1a6226cb67803611102a8d2096f886707ffaaf19994dc636"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "360fbf7d79950bcf65fd53ee82897e8a1f7b5304"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "df0491def528e0a6c55e4e752bb547cb718c401c9dea00b0e28dd49bb61a2017"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "b115c34039708b31b878910838cc61b2442185d8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "222aeb4d1ac435db4de84b0717bae50d508abe99d51b4f4e78a726342821bf30"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "aarch64"
git-tree-sha1 = "d261edbc80508c7790c68a09605a305217347344"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SIFDecode.download]]
    sha256 = "a9aff0058e1624c2d0b1bbb8a5f543dccca3fd85619ad74363b0b24ce34493da"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9b4505f090bf51090c904c89e8f2bc5799cb1182"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "04878aff2447e0c1053c322de8d8ec6a482da14bc7ffffab5afb01e72c292ced"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "910c698496dc50660190f083d613dedd214e99f9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "4d12633de89f1b99d4ca7b3aabd0ff3a94267caaf86a0f395e5630170bcd0f95"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8a848203dcee00f542f363b9c24559504883b77"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "064dfe5aa258a5464ba6f27aabd819ca034b84f006f5f34233797a29e941bb02"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "59e14f7ef84d81606098fa3a51ef7821c22bf455"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "64a45046b5f45fca164060d74dd78a7dfc179ecc5d05296e3b3f69674f20c829"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "a9989c4bc378838cc0ef57d60cbdb146e3b98b16"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "6a44f0bdcb3af8eb0762bc65b7cf66e67795ba896754b79f06be553849f2657c"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.i686-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "abbc505559dcb0a7fbe0a4b2ae3b62501a20c122"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "309a7ab8b15bd1461635c8530d6e0cc843b63b0d085846f7771ebdba92e2f51b"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.i686-linux-musl-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "i686"
git-tree-sha1 = "54e52269ce4061fc2619ae148ffa821763813008"
libgfortran_version = "5.0.0"
os = "windows"

    [[SIFDecode.download]]
    sha256 = "fefb10cdcdb36603d8cdfb4e4393778054931ea276fda597a6ff5915898ba21c"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "powerpc64le"
git-tree-sha1 = "915e66705b4628dbfcde020c1051f4e4fbb2e20a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "bc877ff2bccc315be01be5a1aeae3af804d67d5309c4b1a52720e1a63e3e9b3f"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "riscv64"
git-tree-sha1 = "b12174f9a8634eeeba9e28178304e17978fd2dba"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "95e553f636dc768cb239d9e44db46625ddf70057a4cfebecfcf5600abbdbff14"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.riscv64-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "87a66e52dd033068ba333133ea3725221e478ce2"
libgfortran_version = "5.0.0"
os = "macos"

    [[SIFDecode.download]]
    sha256 = "56ea555b2c1232b619f19ca82e8359309caa88a2c5b15dfc0984bc27d9b90698"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "a95d58f3579c0affef5a2d0e3e27219b3f7fdee9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "ca6931054d20cad39d4c9e6c4d1b397173b04136b06fca2836baaa58fc4b3c0c"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "efeb30200fb788203b75b8d071bc213d0f01f4c0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SIFDecode.download]]
    sha256 = "3fda3a682f0858df90f4dc02eb85573c0d82ea0c578df44d0333b062aa6b74bf"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "9e2d73274d4e4abb3f04a150f8d2ad500cd21ceb"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SIFDecode.download]]
    sha256 = "fc46f0651edb60181102856185186dd271e812c336fc56070ef3b4582a242cfa"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SIFDecode]]
arch = "x86_64"
git-tree-sha1 = "526ebeb60a3a154f65bcea294fd4e65f819969d9"
libgfortran_version = "5.0.0"
os = "windows"

    [[SIFDecode.download]]
    sha256 = "878bf1adf4a3be4ab24a8c5af560f96b77c16829e1e213e186c8bc3ef7a0e937"
    url = "https://github.com/JuliaBinaryWrappers/SIFDecode_jll.jl/releases/download/SIFDecode-v3.1.1+0/SIFDecode.v3.1.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
